spring.application.name=demo
# ====================================================
# Configuração do Servidor Web
# ====================================================
server.port=8080

# ====================================================
# Configuração do H2 Database (em memória)
# H2 é usado para desenvolvimento e testes
# ====================================================
spring.datasource.url=jdbc:h2:mem:bookdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=password

# Habilita o console do H2 para visualização (Acessar em http://localhost:8080/h2-console)
spring.h2.console.enabled=true

# ====================================================
# Configuração do JPA/Hibernate
# ====================================================
# Define o dialeto SQL para o H2
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

# ddl-auto=update: Cria ou atualiza as tabelas automaticamente na inicialização
spring.jpa.hibernate.ddl-auto=update

# Exibir o SQL gerado no console (útil para debug)
spring.jpa.show-sql=true

# Formatar o SQL para melhor leitura
spring.jpa.properties.hibernate.format_sql=true